import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useUser } from "../../../hooks/useUser";

interface HistoryItem {
  id: string;
  invoice_id: string;
  generated_at: string;
}

export default function RecurringInvoiceHistoryPage() {
  const router = useRouter();
  const { id } = router.query;
  const { user, loading } = useUser();

  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [loadingHistory, setLoadingHistory] = useState(true);

  useEffect(() => {
    if (!user || !id) return;

    // Placeholder: if you later add a dedicated history table,
    // this can call /api/recurring-invoices/:id/history.
    async function load() {
      // For now, just leave as empty timeline scaffold.
      setHistory([]);
      setLoadingHistory(false);
    }

    load();
  }, [user, id]);

  if (loading || loadingHistory) return <div className="p-6">Loading…</div>;
  if (!user) return <div className="p-6">Please sign in</div>;

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-2xl font-semibold">Generation History</h1>
        <p className="text-sm text-gray-500">
          Timeline of invoices generated by this recurring schedule.
        </p>
      </div>

      <div className="rounded-md border p-4">
        {history.length === 0 ? (
          <p className="text-sm text-gray-500">
            No history recorded yet. Once this schedule runs, generated invoices
            will appear here.
          </p>
        ) : (
          <ul className="space-y-3 text-sm">
            {history.map((h) => (
              <li
                key={h.id}
                className="flex items-center justify-between border-b pb-2 last:border-b-0 last:pb-0"
              >
                <div>
                  <div className="font-medium">
                    Invoice #{h.invoice_id.slice(0, 8)}
                  </div>
                  <div className="text-gray-500">
                    Generated at {h.generated_at}
                  </div>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
