// lib/constants/ukCoa.js
// Canonical UK chart of accounts template, derived from live chart_of_account_entries export.
// This is *template* data: no ids, no client-specific flags.

export const UK_COA = [
  // --- Balance Sheet: Fixed Assets ---
{
  account_code: "1000",
  account_name: "Office Equipment",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1200",
  account_name: "Accounts Receivable",
  account_type: "ACCOUNTS_RECEIVABLE",
  hmrc_bucket: "assets",
  sa_bucket: null,
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: true,
},

{
  account_code: "1210",
  account_name: "Accounts Receivable",
  account_type: "ACCOUNTS_RECEIVABLE",
  hmrc_bucket: "assets",
  sa_bucket: null,
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: true,
},
{
  account_code: "2110",
  account_name: "Accounts Payable",
  account_type: "ACCOUNTS_PAYABLE",
  hmrc_bucket: "liabilities",
  sa_bucket: null,
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: true,
},
{
  account_code: "2300",
  account_name: "Loans Liabiity",   // must match DB string exactly
  account_type: "LIABILITY",
  hmrc_bucket: "liabilities",
  sa_bucket: null,
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: true,
},


{
  account_code: "2200",
  account_name: "VAT Control",
  account_type: "VAT_CONTROL",
  hmrc_bucket: "vat",
  sa_bucket: null,
  is_system: true,
  is_control_account: true,
  is_bank_account: false,
  is_system_protected: true,
},

{
  account_code: "1001",
  account_name: "Computer Equipment",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1002",
  account_name: "Tools",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1003",
  account_name: "Furniture",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1004",
  account_name: "Machinery",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1099",
  account_name: "Accumulated Depreciation",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset_contra",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1010",
  account_name: "Buildings",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "1011",
  account_name: "Office Improvements",
  account_type: "ASSET",
  hmrc_bucket: "fixed_asset",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

  // --- P&L: Income ---
  {
    account_code: "4000",
    account_name: "Sales",
    account_type: "INCOME",
    hmrc_bucket: "income",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "4001",
    account_name: "Other Income",
    account_type: "INCOME",
    hmrc_bucket: "income",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
  account_code: "4002",
  account_name: "Refunds Received",
  account_type: "INCOME",
  hmrc_bucket: "non_trading_income",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "4003",
  account_name: "Grants / Government Support",
  account_type: "INCOME",
  hmrc_bucket: "non_trading_income",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "4004",
  account_name: "Insurance Payouts",
  account_type: "INCOME",
  hmrc_bucket: "non_trading_income",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "4005",
  account_name: "Asset Sale Proceeds",
  account_type: "INCOME",
  hmrc_bucket: "non_trading_income",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "4006",
  account_name: "Director Loan – Interest Charged",
  account_type: "INCOME",
  hmrc_bucket: "non_trading_income",
  is_system: true,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

  

  // --- P&L: Allowable expenses ---
  {
    account_code: "5000",
    account_name: "Materials",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5001",
    account_name: "Subcontractors",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5002",
    account_name: "Tools & Equipment",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5003",
    account_name: "Repairs & Maintenance",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5004",
    account_name: "Fuel",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5005",
    account_name: "Motor Expenses",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5006",
    account_name: "Travel & Subsistence",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5007",
    account_name: "Rent",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5008",
    account_name: "Utilities",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5009",
    account_name: "Phone & Internet",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5010",
    account_name: "Bank Charges",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5011",
    account_name: "Charges",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5012",
    account_name: "Insurance",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5013",
    account_name: "Advertising & Marketing",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5014",
    account_name: "Professional Fees",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5015",
    account_name: "Software & Subscriptions",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5016",
    account_name: "Office Supplies",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5017",
    account_name: "Postage & Delivery",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5018",
    account_name: "Printing & Stationery",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5019",
    account_name: "Staff Wages",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5020",
    account_name: "Employer NI",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5021",
    account_name: "Employer Pension Contributions",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5022",
    account_name: "Director Salary (PAYE)",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5023",
    account_name: "Stock Purchases",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5024",
    account_name: "Packaging",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5025",
    account_name: "Delivery to Customers",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5026",
    account_name: "Plant & Machinery",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5027",
    account_name: "Vehicles",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5028",
    account_name: "Computers & IT Equipment",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5029",
    account_name: "Fixtures & Fittings",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5030",
    account_name: "Director Loan – Interest Paid",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },

  // --- P&L: Disallowable expenses (P&L view) ---
  {
    account_code: "5031",
    account_name: "Clothing",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable", // matches live CoA export
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5032",
    account_name: "Groceries",
    account_type: "EXPENSE",
    hmrc_bucket: "disallowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5033",
    account_name: "Entertainment",
    account_type: "EXPENSE",
    hmrc_bucket: "disallowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5034",
    account_name: "Gifts",
    account_type: "EXPENSE",
    hmrc_bucket: "disallowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5035",
    account_name: "Personal Spending",
    account_type: "EXPENSE",
    hmrc_bucket: "disallowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
  account_code: "5036",
  account_name: "Cash Withdrawals",
  account_type: "ASSET",
  hmrc_bucket: "balance_sheet",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

  {
    account_code: "5037",
    account_name: "Fines & Penalties",
    account_type: "EXPENSE",
    hmrc_bucket: "disallowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5040",
    account_name: "Client Entertainment",
    account_type: "EXPENSE",
    hmrc_bucket: "disallowable",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },

  // --- DLA / director-related (balance sheet view) ---
  {
    account_code: "5038",
    account_name: "Director Payments (Disallowable)",
    account_type: "ASSET",
    hmrc_bucket: "balance_sheet",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5039",
    account_name: "Director Personal Expenses",
    account_type: "ASSET",
    hmrc_bucket: "balance_sheet",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "5041",
    account_name: "Director Loan – Drawings",
    account_type: "ASSET",
    hmrc_bucket: "balance_sheet",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },

  // --- Loans (you added these) ---
  {
    account_code: "5042",
    account_name: "Loans Interest Expense",
    account_type: "EXPENSE",
    hmrc_bucket: "allowable",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
{
  account_code: "5043",
  account_name: "Loan Liability Adjustment",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: null,
  description: "Adjustment to loan liability balances.",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},


  // --- System movement accounts (non-P&L) ---
  {
    account_code: "9000",
    account_name: "Transfers",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9001",
    account_name: "Internal Transfers",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9002",
    account_name: "Transfer Between Accounts",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9003",
    account_name: "Returned Direct Debit",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9004",
    account_name: "Bank Transfer In",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9005",
    account_name: "Bank Transfer Out",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9006",
    account_name: "Card Payment",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9007",
    account_name: "Cash Deposit",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9008",
    account_name: "VAT Paid",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9009",
    account_name: "VAT Collected",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9010",
    account_name: "VAT Adjustment",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9011",
    account_name: "CIS Deducted",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9012",
    account_name: "CIS Suffered",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9013",
    account_name: "Corporation Tax Payment",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9014",
    account_name: "Corporation Tax Refund",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9015",
    account_name: "SA Payment",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9016",
    account_name: "SA Refund",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9017",
    account_name: "Director Loan – Repayments",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9018",
    account_name: "Loan Repayments",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9019",
    account_name: "Credit Card Payments",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "9020",
    account_name: "Uncategorised",
    account_type: "SYSTEM",
    hmrc_bucket: "ignore",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },

  // --- Control / balance sheet / banks / equity / VAT / AR / AP / loans ---
  {
    account_code: "1100",
    account_name: "Bank",
    account_type: "BANK",
    hmrc_bucket: "balance_sheet",
    is_system: true,
    is_control_account: false,
    is_bank_account: true,
    is_system_protected: true,
  },
  
  {
    account_code: "1200",
    account_name: "Accounts Receivable",
    account_type: "ACCOUNTS_RECEIVABLE",
    hmrc_bucket: "assets",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: true,
  },
  {
    account_code: "2100",
    account_name: "Accounts Payable",
    account_type: "ACCOUNTS_PAYABLE",
    hmrc_bucket: "liabilities",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: true,
  },
  {
    account_code: "2200",
    account_name: "VAT Control",
    account_type: "VAT_CONTROL",
    hmrc_bucket: "vat",
    is_system: true,
    is_control_account: true,
    is_bank_account: false,
    is_system_protected: true,
  },


  {
    account_code: "3000",
    account_name: "Opening Equity",
    account_type: "EQUITY",
    hmrc_bucket: "equity",
    is_system: false,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: false,
  },
  {
    account_code: "3200",
    account_name: "Retained Earnings",
    account_type: "EQUITY",
    hmrc_bucket: "equity",
    is_system: true,
    is_control_account: false,
    is_bank_account: false,
    is_system_protected: true,
  },
  {
    account_code: "9998",
    account_name: "Suspense",
    account_type: "CONTROL",
    hmrc_bucket: "control",
    is_system: true,
    is_control_account: true,
    is_bank_account: false,
    is_system_protected: true,
  },
  {
    account_code: "9999",
    account_name: "Rounding",
    account_type: "CONTROL",
    hmrc_bucket: "control",
    is_system: true,
    is_control_account: true,
    is_bank_account: false,
    is_system_protected: true,
  },
  // --- SA103: Self-Employment Income ---
{
  account_code: "4100",
  account_name: "Self-Employment Turnover",
  account_type: "INCOME",
  hmrc_bucket: "income",
  sa_bucket: "sa_se_turnover",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

// --- SA103: Self-Employment Expenses ---
{
  account_code: "5100",
  account_name: "SE – Materials",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5101",
  account_name: "SE – Subcontractors",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5102",
  account_name: "SE – Travel",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5103",
  account_name: "SE – Rent",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5104",
  account_name: "SE – Utilities",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5105",
  account_name: "SE – Phone & Internet",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5106",
  account_name: "SE – Insurance",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5107",
  account_name: "SE – Bank Charges",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5108",
  account_name: "SE – Professional Fees",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5109",
  account_name: "SE – Office Supplies",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5110",
  account_name: "SE – Disallowable Expenses",
  account_type: "EXPENSE",
  hmrc_bucket: "disallowable",
  sa_bucket: "sa_se_disallowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5111",
  account_name: "SE – Capital Allowances",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_capital_allowance",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5112",
  account_name: "SE – Adjustments",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_se_adjustment",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

// --- SA105: Property Income ---
{
  account_code: "4200",
  account_name: "Rental Income",
  account_type: "INCOME",
  hmrc_bucket: "income",
  sa_bucket: "sa_property_rental_income",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

// --- SA105: Property Expenses ---
{
  account_code: "5200",
  account_name: "Property Repairs",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5201",
  account_name: "Property Insurance",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5202",
  account_name: "Property Management Fees",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5203",
  account_name: "Mortgage Interest",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_mortgage_interest",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5204",
  account_name: "Property Utilities",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5205",
  account_name: "Property Cleaning",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5206",
  account_name: "Property Advertising",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_allowable_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5207",
  account_name: "Property Capital Allowances",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_capital_allowance",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5208",
  account_name: "Property Losses",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_loss",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

// --- SA105: FHL ---
{
  account_code: "4300",
  account_name: "FHL Income",
  account_type: "INCOME",
  hmrc_bucket: "income",
  sa_bucket: "sa_property_fhl_income",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5300",
  account_name: "FHL Expenses",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_fhl_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},

// --- SA105: Rent-a-Room ---
{
  account_code: "4400",
  account_name: "Rent-a-Room Income",
  account_type: "INCOME",
  hmrc_bucket: "income",
  sa_bucket: "sa_property_rent_a_room_income",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "5400",
  account_name: "Rent-a-Room Expenses",
  account_type: "EXPENSE",
  hmrc_bucket: "allowable",
  sa_bucket: "sa_property_rent_a_room_expense",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
// --- P&L: R&D Expenditure ---
{
  account_code: "6000",
  account_name: "R&D Staff Costs",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6001",
  account_name: "R&D Subcontractors",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6002",
  account_name: "R&D Materials",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6003",
  account_name: "R&D Software & Cloud",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6004",
  account_name: "R&D Utilities & Overheads",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6005",
  account_name: "R&D Prototypes & Testing",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6006",
  account_name: "R&D Capitalised Costs",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_expenditure",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},
{
  account_code: "6007",
  account_name: "R&D Grants / Subsidies",
  account_type: "EXPENSE",
  hmrc_bucket: "rd_income_offset",
  is_system: false,
  is_control_account: false,
  is_bank_account: false,
  is_system_protected: false,
},




];
