// pages/legal/terms.js
import React from "react";

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-10">
      <h1 className="text-3xl font-bold mb-6">Terms &amp; Conditions</h1>
      <p className="text-sm text-slate-500 mb-8">
        Last updated: {new Date().toLocaleDateString("en-GB")}
      </p>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
        <p className="mb-3">
          These Terms and Conditions (&quot;Terms&quot;) govern your access to
          and use of the ProfitLens platform, website, and related services
          (collectively, the &quot;Service&quot;), provided by{" "}
          <strong>ProfitLens Technologies Ltd</strong>, trading as{" "}
          <strong>ProfitLens UK</strong> (&quot;we&quot;, &quot;us&quot;,
          &quot;our&quot;).
        </p>
        <p className="mb-3">
          By creating an account, accessing the Service, or using any part of
          the platform, you agree to be bound by these Terms. If you do not
          agree, you must not use the Service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">2. About Us</h2>
        <p className="mb-3">
          The Service is operated by <strong>ProfitLens Technologies Ltd</strong>
          , trading as <strong>ProfitLens UK</strong>, a company intended to be
          registered in England and Wales. Company formation details will be
          added on completion of incorporation.
        </p>
        <p className="mb-1">
          For enquiries relating to these Terms, you can contact us at:
        </p>
        <p className="mb-3">
          <strong>Email:</strong>{" "}
          <a
            href="mailto:support@profitlens.co.uk"
            className="text-blue-600 underline"
          >
            support@profitlens.co.uk
          </a>
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">
          3. Nature of the Service (Important Disclaimer)
        </h2>
        <p className="mb-3">
          ProfitLens UK provides bookkeeping tools, financial dashboards, and
          tax-estimation features for small businesses, sole traders, and
          limited companies.
        </p>
        <p className="mb-3">
          The Service includes, without limitation:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-1">
          <li>Bank statement and transaction import tools</li>
          <li>Automated transaction categorisation</li>
          <li>Financial summaries and dashboards</li>
          <li>Tax estimation and scenario modelling</li>
          <li>Document and receipt storage</li>
          <li>Reporting and export tools</li>
        </ul>
        <p className="mb-3 font-semibold">
          ProfitLens UK does <span className="underline">not</span> provide:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-1">
          <li>Tax advice</li>
          <li>Accounting advice</li>
          <li>Legal advice</li>
          <li>Financial advice</li>
          <li>Regulated professional services</li>
        </ul>
        <p className="mb-3">
          All tax calculations, estimates, and outputs generated by the Service
          are for informational purposes only. They are not a substitute for
          professional advice or for your own review of your financial position
          and tax obligations.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">
          4. User Responsibilities and No Liability for Tax Errors
        </h2>
        <p className="mb-3">
          You acknowledge and agree that you are solely responsible for:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-1">
          <li>The accuracy and completeness of all data you enter or upload</li>
          <li>
            Reviewing all calculations, estimates, and outputs before relying on
            them
          </li>
          <li>
            Preparing and submitting all required tax returns and filings to
            HMRC or other authorities
          </li>
          <li>Complying with all applicable tax and accounting laws</li>
          <li>Seeking advice from a qualified professional where necessary</li>
        </ul>
        <p className="mb-3">
          To the fullest extent permitted by law, we do not accept any liability
          for:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-1">
          <li>Incorrect tax calculations or estimates</li>
          <li>Incorrect or incomplete categorisation of transactions</li>
          <li>Missed deadlines, penalties, or interest charged by HMRC</li>
          <li>Losses arising from reliance on the Service</li>
          <li>Errors or omissions in data provided or uploaded by you</li>
          <li>Errors caused by third-party integrations or bank feeds</li>
        </ul>
        <p className="mb-3">
          You must independently verify all figures and, where appropriate,
          obtain professional advice before filing tax returns or making
          financial decisions based on information provided by the Service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">
          5. Account Registration and Security
        </h2>
        <p className="mb-3">
          To use the Service, you must create an account and provide accurate,
          current, and complete information. You are responsible for maintaining
          the confidentiality of your login credentials and for all activity
          that occurs under your account.
        </p>
        <p className="mb-3">
          You agree to notify us immediately if you suspect any unauthorised use
          of your account or any other breach of security. We are not liable for
          any loss or damage arising from your failure to safeguard your account
          credentials.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">
          6. Subscription Plans, Billing and Free Trial
        </h2>
        <p className="mb-3">
          ProfitLens UK is provided on a subscription basis. We may offer
          monthly and annual plans, as well as a free trial period for new
          users. Details of current plans and pricing are available within the
          Service or on our website.
        </p>
        <p className="mb-3">
          If a free trial is offered, it will run for the duration specified at
          signup (for example, 24 hours) and will automatically convert into a
          paid subscription unless you cancel before the end of the trial
          period. Free trials are limited to one per user unless we explicitly
          state otherwise.
        </p>
        <p className="mb-3">
          By starting a subscription, you authorise us and our payment provider
          to charge the applicable fees to your chosen payment method on a
          recurring basis (monthly or annually, as selected) until you cancel.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">7. Cancellations and Refunds</h2>
        <p className="mb-3">
          You may cancel your subscription at any time through your account
          settings. Cancellation takes effect at the end of the current billing
          period, and you will retain access to the Service until that time.
        </p>
        <p className="mb-3">
          We do not provide refunds for partial billing periods, unused time, or
          failure to cancel before renewal, except where required by law or as
          set out in our separate Refund Policy. In the event of a conflict
          between these Terms and the Refund Policy, the Refund Policy will
          prevail in relation to refunds.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">8. Acceptable Use</h2>
        <p className="mb-3">
          You agree to use the Service only for lawful purposes and in
          accordance with our Acceptable Use Policy. You must not:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-1">
          <li>Use the Service to commit or facilitate fraud or tax evasion</li>
          <li>Upload unlawful, harmful, or inappropriate content</li>
          <li>
            Interfere with or disrupt the operation or security of the Service
          </li>
          <li>
            Attempt to gain unauthorised access to any part of the platform or
            related systems
          </li>
          <li>
            Reverse-engineer, decompile, or otherwise attempt to extract the
            source code of the Service
          </li>
        </ul>
        <p className="mb-3">
          We may suspend or terminate your access to the Service if we believe
          you have breached these Terms or our Acceptable Use Policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">9. Intellectual Property</h2>
        <p className="mb-3">
          All intellectual property rights in the Service, including the
          software, design, logos, branding, and content (excluding your own
          data), are owned by or licensed to ProfitLens Technologies Ltd.
        </p>
        <p className="mb-3">
          We grant you a limited, non-exclusive, non-transferable licence to use
          the Service for your own internal business or personal bookkeeping
          purposes, in accordance with these Terms. You may not copy, modify,
          distribute, sell, or lease any part of the Service, nor may you
          reverse-engineer or attempt to extract the source code, except where
          such restrictions are prohibited by law.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">10. Data Protection</h2>
        <p className="mb-3">
          We process personal data in accordance with UK GDPR and the Data
          Protection Act 2018. Our collection and use of personal data is
          described in our Privacy Policy, which forms part of these Terms.
        </p>
        <p className="mb-3">
          Where we process personal data on your behalf, our Data Processing
          Agreement also applies. By using the Service, you agree to the terms
          of our Privacy Policy and Data Processing Agreement.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">11. Limitation of Liability</h2>
        <p className="mb-3">
          Nothing in these Terms excludes or limits liability for death or
          personal injury caused by negligence, fraud or fraudulent
          misrepresentation, or any other liability that cannot be excluded
          under UK law.
        </p>
        <p className="mb-3">
          To the fullest extent permitted by law, we exclude all warranties,
          representations, and conditions, whether express or implied, in
          relation to the Service. The Service is provided on an &quot;as is&quot; and
          &quot;as available&quot; basis.
        </p>
        <p className="mb-3">
          Subject to the first paragraph of this section, our total aggregate
          liability to you arising out of or in connection with the Service or
          these Terms (whether in contract, tort, negligence, or otherwise)
          shall be limited to the total fees paid by you to us in the 12 months
          preceding the event giving rise to the claim.
        </p>
        <p className="mb-3">
          We are not liable for any indirect, consequential, or special loss,
          including loss of profit, revenue, data, or business opportunities,
          whether arising in contract, tort (including negligence), or
          otherwise, even if we have been advised of the possibility of such
          loss or damage.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">12. Service Availability</h2>
        <p className="mb-3">
          We aim to provide a high level of availability for the Service but do
          not guarantee that the Service will be uninterrupted, error-free, or
          free from defects. Details of our uptime targets and support response
          commitments are set out in our Service Level Agreement (SLA).
        </p>
        <p className="mb-3">
          We may suspend or restrict access to the Service temporarily to carry
          out maintenance, updates, or improvements. Where reasonably possible,
          we will provide notice of planned maintenance.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">13. Termination</h2>
        <p className="mb-3">
          You may stop using the Service at any time and may cancel your
          subscription in accordance with Section 7 (Cancellations and Refunds).
        </p>
        <p className="mb-3">
          We may suspend or terminate your access to the Service, or close your
          account, if:
        </p>
        <ul className="list-disc pl-6 mb-3 space-y-1">
          <li>You materially breach these Terms or any related policy</li>
          <li>You use the Service in a way that is unlawful or harmful</li>
          <li>You fail to pay subscription fees when due</li>
          <li>We are required to do so by law or regulation</li>
        </ul>
        <p className="mb-3">
          Upon termination, your right to access and use the Service will
          cease. We may retain certain data as required by law or as described
          in our Privacy Policy and Data Processing Agreement.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">
          14. Changes to These Terms
        </h2>
        <p className="mb-3">
          We may update these Terms from time to time, for example to reflect
          changes in the Service, legal requirements, or business practices. We
          will notify you of any material changes by email or via the Service.
        </p>
        <p className="mb-3">
          The updated Terms will take effect on the date specified in the
          notice. If you continue to use the Service after that date, you will
          be deemed to have accepted the updated Terms.
        </p>
      </section>

      <section className="mb-12">
        <h2 className="text-xl font-semibold mb-3">15. Governing Law</h2>
        <p className="mb-3">
          These Terms and any dispute or claim arising out of or in connection
          with them or their subject matter or formation (including
          non-contractual disputes or claims) shall be governed by and
          construed in accordance with the laws of England and Wales.
        </p>
        <p className="mb-3">
          The courts of England and Wales shall have exclusive jurisdiction to
          settle any dispute or claim arising out of or in connection with these
          Terms or their subject matter or formation.
        </p>
      </section>

      <p className="text-sm text-slate-500">
        If you have any questions about these Terms &amp; Conditions, please
        contact us at{" "}
        <a
          href="mailto:support@profitlens.co.uk"
          className="text-blue-600 underline"
        >
          support@profitlens.co.uk
        </a>
        .
      </p>
    </div>
  );
}
