// lib/pdf/templates/ct600.js
import { createPdfBuffer, storePdfAndRecord } from "../engine";

export async function generateCt600Pdf({
  clientId,
  year,
  filename,
  createdBy,
  companyDetails,
  ctSummary,
}) {
  const buffer = await createPdfBuffer((doc) => {
    doc.fontSize(20).text("CT600 Corporation Tax", { align: "center" }).moveDown();

    if (companyDetails?.name) {
      doc.fontSize(12).text(`Company: ${companyDetails.name}`);
    }
    if (clientId) doc.text(`Client ID: ${clientId}`);
    if (year) doc.text(`Year: ${year}`);
    doc.moveDown();

    doc.fontSize(14).text("Summary", { underline: true }).moveDown(0.5);
    if (ctSummary) {
      Object.entries(ctSummary).forEach(([label, value]) => {
        doc.fontSize(12).text(`${label}: ${value}`);
      });
    }

    doc.moveDown(2);
    doc.fontSize(10).fillColor("gray")
      .text("Generated by ProfitLens", { align: "right" });
  });

  const record = await storePdfAndRecord({
    clientId,
    type: "ct600",
    periodStart: null,
    periodEnd: null,
    year,
    taxYear: null,
    filename,
    createdBy,
    metadata: {
      companyDetails: companyDetails || null,
      summary: ctSummary || null,
    },
    buffer,
  });

  return record;
}
