// lib/pdf/templates/profile.js
import { createPdfBuffer, storePdfAndRecord } from "../engine";

export async function generateProfilePdf({
  clientId,
  year,
  filename,
  createdBy,
  profileSummary,
  companyDetails,
}) {
  const buffer = await createPdfBuffer((doc) => {
    doc.fontSize(20).text("Client Profile Summary", { align: "center" }).moveDown();

    if (companyDetails?.name) {
      doc.fontSize(12).text(`Client: ${companyDetails.name}`);
    }
    if (clientId) {
      doc.text(`Client ID: ${clientId}`);
    }
    if (year) {
      doc.text(`Year: ${year}`);
    }

    doc.moveDown();
    doc.fontSize(14).text("Summary", { underline: true }).moveDown(0.5);

    if (profileSummary) {
      Object.entries(profileSummary).forEach(([label, value]) => {
        doc.fontSize(12).text(`${label}: ${value}`);
      });
    }

    doc.moveDown(2);
    doc.fontSize(10).fillColor("gray")
      .text("Generated by ProfitLens", { align: "right" });
  });

  const record = await storePdfAndRecord({
    clientId,
    type: "profile",
    periodStart: null,
    periodEnd: null,
    year,
    taxYear: null,
    filename,
    createdBy,
    metadata: {
      profileSummary: profileSummary || null,
      companyDetails: companyDetails || null,
    },
    buffer,
  });

  return record;
}
