// lib/pdf/templates/vat.js
import { createPdfBuffer, storePdfAndRecord } from "../engine";

export async function generateVatPdf({
  clientId,
  periodStart,
  periodEnd,
  year,
  taxYear,
  filename,
  createdBy,

  // VAT payload
  vatBoxes = {},
  transactions = [],
  adjustments = [],
  companyDetails = {},
}) {
  const buffer = await createPdfBuffer((doc) => {
    //
    // HEADER — FULL CLIENT IDENTITY
    //
    doc.fontSize(20).text("VAT Return", { align: "center" }).moveDown();

    doc.fontSize(12);

    if (companyDetails?.name) doc.text(`Client: ${companyDetails.name}`);
    if (companyDetails?.businessName) doc.text(`Business: ${companyDetails.businessName}`);
    if (companyDetails?.email) doc.text(`Email: ${companyDetails.email}`);
    if (companyDetails?.phone) doc.text(`Phone: ${companyDetails.phone}`);
    if (companyDetails?.address) doc.text(`Address: ${companyDetails.address}`);
    if (companyDetails?.companyNumber) doc.text(`Company Number: ${companyDetails.companyNumber}`);
    if (companyDetails?.vatNumber) doc.text(`VAT Number: ${companyDetails.vatNumber}`);

    doc.text(`Client ID: ${clientId}`);

    if (taxYear) doc.text(`Tax Year: ${taxYear}`);

    if (periodStart && periodEnd) {
      doc.text(`Period: ${periodStart} to ${periodEnd}`);
    }

    doc.moveDown();

    //
    // VAT BOXES
    //
    doc.fontSize(14).text("VAT Boxes", { underline: true }).moveDown(0.5);

    const boxLabels = {
      box1: "VAT due on sales",
      box2: "VAT due on acquisitions",
      box3: "Total VAT due (1 + 2)",
      box4: "VAT reclaimed on purchases",
      box5: "Net VAT to pay (3 − 4)",
      box6: "Total sales (net)",
      box7: "Total purchases (net)",
      box8: "EU supplies (net)",
      box9: "EU acquisitions (net)",
    };

    Object.entries(boxLabels).forEach(([key, label]) => {
      const value = vatBoxes[key];
      doc.fontSize(12).text(`${label}: £${Number(value || 0).toFixed(2)}`);
    });

    //
    // ADJUSTMENTS
    //
    if (adjustments.length > 0) {
      doc.moveDown();
      doc.fontSize(14).text("Adjustments", { underline: true }).moveDown(0.5);

      adjustments.forEach((adj) => {
        doc.fontSize(12).text(
          `Box ${adj.box}: £${Number(adj.amount || 0).toFixed(2)} — ${
            adj.reason || "No reason provided"
          }`
        );
      });
    }

    //
    // TRANSACTIONS (NEW PAGE)
    //
    if (transactions.length > 0) {
      doc.addPage();
      doc.fontSize(16).text("VAT Transactions", { underline: true }).moveDown();

      transactions.forEach((tx) => {
        const net = Number(tx.amount || 0) - Number(tx.vat_amount || 0);
        const vat = Number(tx.vat_amount || 0);

        doc.fontSize(12).text(
          `${tx.date} | ${tx.description} | Net: £${net.toFixed(
            2
          )} | VAT: £${vat.toFixed(2)}`
        );
      });
    }

    //
    // FOOTER
    //
    doc.moveDown(2);
    doc.fontSize(10).fillColor("gray").text("Generated by ProfitLens", {
      align: "right",
    });
  });

  //
  // STORE PDF
  //
  const record = await storePdfAndRecord({
    clientId,
    type: "vat",
    periodStart,
    periodEnd,
    year,
    taxYear,
    filename,
    createdBy,
    metadata: {
      vatBoxes,
      transactions,
      adjustments,
      companyDetails,
    },
    buffer,
  });

  return record;
}
