// lib/pdf/templates/vat.js
import { createPdfBuffer, storePdfAndRecord } from "../engine";

export async function generateVatPdf({
  clientId,
  periodStart,
  periodEnd,
  year,
  taxYear,
  filename,
  createdBy,
  vatBoxes,
  companyDetails,
  totals,
}) {
  const buffer = await createPdfBuffer((doc) => {
    doc.fontSize(20).text("VAT Return", { align: "center" }).moveDown();
    if (companyDetails?.name) {
      doc.fontSize(12).text(`Client: ${companyDetails.name}`);
    }
    if (clientId) {
      doc.text(`Client ID: ${clientId}`);
    }
    if (taxYear) {
      doc.text(`Tax year: ${taxYear}`);
    }
    if (periodStart && periodEnd) {
      doc.text(`Period: ${periodStart} to ${periodEnd}`);
    }
    doc.moveDown();

    doc.fontSize(14).text("VAT Boxes", { underline: true }).moveDown(0.5);

    if (vatBoxes) {
      Object.entries(vatBoxes).forEach(([box, value]) => {
        doc.fontSize(12).text(`${box}: ${value}`);
      });
    }

    if (totals) {
      doc.moveDown();
      doc.fontSize(14).text("Totals", { underline: true }).moveDown(0.5);
      Object.entries(totals).forEach(([label, value]) => {
        doc.fontSize(12).text(`${label}: ${value}`);
      });
    }

    doc.moveDown(2);
    doc.fontSize(10).fillColor("gray")
      .text("Generated by ProfitLens", { align: "right" });
  });

  const record = await storePdfAndRecord({
    clientId,
    type: "vat",
    periodStart,
    periodEnd,
    year,
    taxYear,
    filename,
    createdBy,
    metadata: {
      companyDetails: companyDetails || null,
      vatBoxes: vatBoxes || null,
      totals: totals || null,
    },
    buffer,
  });

  return record;
}
